### ISSUE TITLE
Add ES module support

### ISSUE THREAD

**Issue by FuketsuBaka** [qntm/abcdefghijklmnopqrstuvwxyz#44]
`Error [ERR_REQUIRE_ESM]: require() of ES Module .\node_modules\abcdefghijklmnopqrstuvwxyz\src\abcdefghijklmnopqrstuvwxyz.js from .\test.js not supported.`

**Comment by qntm** [comment]
`abcdefghijklmnopqrstuvwxyz` is already a [pure ESM package](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c). CommonJS support was [dropped in version 3.0.0](https://github.com/qntm/abcdefghijklmnopqrstuvwxyz/blob/main/CHANGELOG.md#3xx).
