### ISSUE TITLE
Feature Request: Internationalization (i18n)

### ISSUE THREAD

**Issue by hugolgst** [qntm/abcdefghijklmnopqrstuvwxyz#6]
Hello,

Could you internationalise this package, so we can get the Cyrillic for example ?

Thank you,
Hugo

**Comment by qntm** [comment]
`abcdefghijklmnopqrstuvwxyz` specifically exports - and is documented as exporting - the **English** alphabet, which is 'abcdefghijklmnopqrstuvwxyz', even in Russia.
