### ISSUE TITLE
Feature request : export as array

### ISSUE THREAD

**Issue by siffreinsg** [qntm/abcdefghijklmnopqrstuvwxyz#8]
Hi !
Would be great if we could export the alphabet as an array instead of a string!
Thanks;

**Comment by qntm** [comment]
This would clutter the API, which is intentionally very streamlined. Suggest using:

```js
import { abcdefghijklmnopqrstuvwxyz } from 'abcdefghijklmnopqrstuvwxyz'

const arr = abcdefghijklmnopqrstuvwxyz.split('')
// ...
```
