### ISSUE TITLE
Feature request : some utils

### ISSUE THREAD

**Issue by siffreinsg** [qntm/abcdefghijklmnopqrstuvwxyz#9]
Hi again! 
I'd like to perform some operation on the latin alphabet such as "what is the position of this letter in the alphabet" or "what is the nth letter of the alphabet". I suggest implementing some utils function such as alphabet.getLetter(31) to get the 31th letter.

Thanks,
Siffrein

**Comment by qntm** [comment]
The JavaScript string exported by `abcdefghijklmnopqrstuvwxyz` already provides exactly this functionality.

```js
import { abcdefghijklmnopqrstuvwxyz } from 'abcdefghijklmnopqrstuvwxyz'

console.log(abcdefghijklmnopqrstuvwxyz[23]) // 'x'
console.log(abcdefghijklmnopqrstuvwxyz.indexOf('v')) // 21
```
